import 'package:flutter/foundation.dart';
import '../annotations/tiger_tag_annotations.dart';

part 'tiger_tag.g.dart';

/// TigerTag model representing a parsed TigerTag RFID tag
///
/// TigerTag uses a proprietary format stored on MIFARE Ultralight tags.
/// This class parses the raw memory bytes into structured data.
///
/// Fields are annotated with @TigerTagField to define parsing logic.
/// The parsing code is generated by build_runner.
@TigerTagClass()
@immutable
class TigerTag {
  // Properties documented with page layout (1 page = 4 bytes)

  /// TigerTag ID - Page 4, byte 0, 4 bytes
  @TigerTagField(
      page: 4, startByte: 0, size: 4, type: TigerTagFieldType.BigEndianInt)
  final int tigerTagID;

  /// Product ID - Page 5, byte 0, 4 bytes
  @TigerTagField(
      page: 5, startByte: 0, size: 4, type: TigerTagFieldType.hexString)
  final String productID;

  /// Material ID - Page 6, byte 0, 2 bytes
  @TigerTagField(
      page: 6, startByte: 0, size: 2, type: TigerTagFieldType.BigEndianInt)
  final int materialID;

  /// First Visual Aspect ID - Page 6, byte 2, 1 byte
  @TigerTagField(
      page: 6, startByte: 2, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int firstVisualAspectID;

  /// Second Visual Aspect ID - Page 6, byte 3, 1 byte
  @TigerTagField(
      page: 6, startByte: 3, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int secondVisualAspectID;

  /// ID Type - Page 7, byte 0, 1 byte
  @TigerTagField(
      page: 7, startByte: 0, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int idType;

  /// Diameter ID - Page 7, byte 1, 1 byte
  @TigerTagField(
      page: 7, startByte: 1, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int diameterID;

  /// ID Brand - Page 7, byte 2, 2 bytes
  @TigerTagField(
      page: 7, startByte: 2, size: 2, type: TigerTagFieldType.BigEndianInt)
  final int idBrand;

  /// First Colour (RGBA) - Page 8, byte 0, 4 bytes
  @TigerTagField(page: 8, startByte: 0, size: 4, type: TigerTagFieldType.bytes)
  final List<int> firstColour;

  /// Measurement Value (Unit Value) - Page 9, byte 0, 3 byte
  @TigerTagField(
      page: 9, startByte: 0, size: 3, type: TigerTagFieldType.BigEndianInt)
  final int measurementValue;

  /// Measurement ID (Unit ID) - Page 9, byte 3, 1 byte
  @TigerTagField(
      page: 9, startByte: 3, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int measurementID;

  /// NozzleTemperatureMin - Page 10, byte 0, 2 bytes
  @TigerTagField(
      page: 10, startByte: 0, size: 2, type: TigerTagFieldType.BigEndianInt)
  final int nozzleTemperatureMin;

  /// NozzleTemperatureMax - Page 10, byte 2, 2 bytes
  @TigerTagField(
      page: 10, startByte: 2, size: 2, type: TigerTagFieldType.BigEndianInt)
  final int nozzleTemperatureMax;

  /// DryTemp - Page 11, byte 0, 1 byte
  @TigerTagField(
      page: 11, startByte: 0, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int dryTemp;

  /// DryTime - Page 11, byte 1, 1 byte
  @TigerTagField(
      page: 11, startByte: 1, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int dryTime;

  /// BedTemperatureMin - Page 11, byte 2, 1 byte
  @TigerTagField(
      page: 11, startByte: 2, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int bedTemperatureMin;

  /// BedTemperatureMax - Page 11, byte 3, 1 byte
  @TigerTagField(
      page: 11, startByte: 3, size: 1, type: TigerTagFieldType.BigEndianInt)
  final int bedTemperatureMax;

  /// Twin Tag Timestamp - Page 12, byte 0, 4 bytes
  @TigerTagField(
      page: 12, startByte: 0, size: 4, type: TigerTagFieldType.BigEndianInt)
  final int twinTagTimestamp;

  // Color 2 - (RGB) - Page 13, byte 0, 3 bytes
  @TigerTagField(page: 13, startByte: 0, size: 3, type: TigerTagFieldType.bytes)
  final List<int> color2;

  // Color 3 - (RGB) - Page 14, byte 0, 3 bytes
  @TigerTagField(page: 14, startByte: 0, size: 3, type: TigerTagFieldType.bytes)
  final List<int> color3;

  // TD value (Decimal / 10) - Page 15, byte 0, 2 bytes
  @TigerTagField(
      page: 15, startByte: 0, size: 2, type: TigerTagFieldType.BigEndianInt)
  final int tdValue;

  /// Raw memory bytes from the tag (for debugging/reference)
  final List<int> rawMemory;

  /// Timestamp when the tag was parsed
  final DateTime parsedAt;

  const TigerTag({
    required this.tigerTagID,
    required this.productID,
    required this.materialID,
    required this.firstVisualAspectID,
    required this.secondVisualAspectID,
    required this.idType,
    required this.diameterID,
    required this.firstColour,
    required this.idBrand,
    required this.measurementID,
    required this.measurementValue,
    required this.nozzleTemperatureMin,
    required this.nozzleTemperatureMax,
    required this.dryTemp,
    required this.dryTime,
    required this.bedTemperatureMin,
    required this.bedTemperatureMax,
    required this.twinTagTimestamp,
    required this.color2,
    required this.color3,
    required this.tdValue,
    required this.rawMemory,
    required this.parsedAt,
  });

  /// Parse raw memory bytes into a TigerTag instance
  ///
  /// [memory] - Raw memory bytes read from the MIFARE Ultralight tag
  /// Returns a TigerTag instance with parsed data, or null if parsing fails
  ///
  /// Implementation is generated by build_runner
  static TigerTag? parse(List<int> memory) => _$parseTigerTag(memory);

  /// Get a formatted hex dump of the raw memory
  String getHexDump() {
    final buffer = StringBuffer();
    for (int i = 0; i < rawMemory.length; i += 16) {
      // Address
      buffer.write('${i.toRadixString(16).padLeft(4, '0')}:  ');

      // Hex values
      for (int j = 0; j < 16; j++) {
        if (i + j < rawMemory.length) {
          buffer
              .write('${rawMemory[i + j].toRadixString(16).padLeft(2, '0')} ');
        } else {
          buffer.write('   ');
        }
        if (j == 7) buffer.write(' '); // Extra space in the middle
      }

      // ASCII representation
      buffer.write(' |');
      for (int j = 0; j < 16 && i + j < rawMemory.length; j++) {
        final byte = rawMemory[i + j];
        if (byte >= 32 && byte <= 126) {
          buffer.write(String.fromCharCode(byte));
        } else {
          buffer.write('.');
        }
      }
      buffer.write('|\n');
    }
    return buffer.toString();
  }

  @override
  String toString() {
    return 'TigerTag(id: $tigerTagID, memorySize: ${rawMemory.length} bytes, parsedAt: $parsedAt)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is TigerTag && other.tigerTagID == tigerTagID;
  }

  @override
  int get hashCode => tigerTagID.hashCode;
}
